### ISSUE TITLE
 No access to the public page

### ISSUE THREAD

**Issue by Amenophis54** [thomasjacquin/allsky-portal#28] opened 2021-08-18 09:33 UTC
Hello, 

After installing and configuring the allsky, I tried to connect to the camera via the link:

http: //raspberryIP/public.php

from the neighbor's computer but unable to display the page.

Thank you

**Comment by thomasjacquin** [comment] 2021-08-18 22:19
Did you replace `raspberryIP` by the IP of your Raspberry Pi? e.g. 192.168.0.25

**Comment by Amenophis54** [comment] 2021-08-19 09:43
Hello Thomas, 
I just tried like this: http://192.162.1.15/public.php

The page displays fine on my computer but on the work computer at my office it does not work.

**Comment by thomasjacquin** [comment] 2021-08-19 17:17
That's because your work computer is on a different network. You can only reach addresses in 192.168.x.x that are on the same network (your home network).
If you want to connect from work, you'll need to use your home public IP (https://whatismyipaddress.com/) and you will probably need to forward port 80 on your home router.

**Comment by EricClaeys** [comment] 2021-08-21 11:44
Amenophis54, 
Since you can get to the website from your home computer, the problem isn't with the AllSky website, but as Thomas said, the problem is that your home network isn't reachable from work.  If you agree, please close this issue.
What some people have done to get around this issue is to copy the allsky-website package to a 3rd party web server, and have allsky lftp the image files to that server.  Then you give other people the URL on that server.
Thanks - Eric

**Closed** 2021-09-28 00:18 UTC
